
public class Problem2 {
	
	/* 20170322 - Sophie Andrews
	 * 
	 * Even Fibonacci numbers
	 * 
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

		By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	 * 
	 * 
	 */
	
	public static void main(String[] args){

		int n = 0;
		int m = 1;
		int seq = 0;
		int sum = 0;

		while (seq < 4000000){

			seq = n + m;
			n = m;
			m = seq;

			if (seq % 2 == 0){
				sum = sum + seq;}

			System.out.print(seq + " ");
		}

		System.out.println();
		System.out.println(sum);
	}

}
