
public class Problem12 {

	/* 20170325 - Sophie Andrews
	 * 
	 * Highly divisible triangular number
	 * 
	 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

			1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

	 * 
	 * Let us list the factors of the first seven triangle numbers:

		 1: 1
		 3: 1,3
		 6: 1,2,3,6
		10: 1,2,5,10
		15: 1,3,5,15
		21: 1,3,7,21
		28: 1,2,4,7,14,28
		We can see that 28 is the first triangle number to have over five divisors.

		What is the value of the first triangle number to have over five hundred divisors?
	 * 
	 * 
	 *	Currently quite inefficient: takes around 20 seconds to run on a 2015 1.6 GHz Intel Core i5 MacBook Air.
	 *
	 */


	public static void triDivisors(int div){

		int[][] factors = new int[2][100000000];
		int tri = 1;
		factors[1][0] = 1;

		for (int i = 0; i < factors[0].length; i++){
			factors[0][i] = 1;
		}

		for (int i = 2; i < factors[0].length; i++){

			if (factors[0][i-2] > 0){

				for (int j = 2*(i-1); j <= factors[0].length; j+=(i-1)){
					factors[0][j-1] += 1;
				}	
			}
		}

		for (int i = 2; tri < factors[1].length; i++){

			factors[1][tri-1] = 1;

			if (factors[1][tri-1] == 1 && factors[0][tri-1] > div){

				System.out.println("First triangle number with over " + div + " divisors is: " + tri);
				break;				
			}
			tri+=i;
		}
	}


	public static void main(String[] args){

		triDivisors(500);

	}
}
